---
title: "P8140: Introduction to Randomized Clinical Trials"
output: html_document
site: "_site.yml"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
  body {
    text-align: justify; 
  }

  h2 {
    font-weight: bold; 
    font-size: 22px; 
    margin-top: 20px; 
    margin-bottom: 20px; 
    margin-left: 0; 
    text-indent: 0; 
  }
  
  p, .course-summary {
    font-size: 18px; 
  }

  .navbar {
    position: fixed;
    width: 100%;
    z-index: 999; 
  }
</style>
<script>
document.addEventListener("DOMContentLoaded", () => {
  const headerHeight = 200; 

  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
      e.preventDefault(); 
      const targetId = this.getAttribute('href');
      const targetElement = document.querySelector(targetId);

      if (targetElement) {
        const elementTop = targetElement.getBoundingClientRect().top + window.pageYOffset;
        const scrollToPosition = elementTop - headerHeight; 

        window.scrollTo({
          top: scrollToPosition,
          behavior: 'smooth'
        });
      }
    });
  });
});
</script>

  <h2>1&#46; Course Overview</h2>

  <p>This course covers the fundamental methods and concepts essential for conducting randomized clinical trials, including protocol development, randomization, blindedness, patient recruitment, informed consent, compliance, sample size determination, crossovers, and collaborative trials. </p>
</p>
  
  <h2>2&#46; Trial Proposal</h2>

<div>
  <h2>Duloxetine Versus Escitalopram in Generalized Anxiety Disorder: A Randomized Controlled Trial</h2>

  <p>
As part of the coursework, I prepared and submitted a protocol for a hypothetical clinical trial, applying the principles learned throughout the course.

This project proposes a randomized, phase 3 clinical trial to directly compare the efficacy of Duloxetine and Escitalopram, two first-line pharmacotherapies, in reducing anxiety symptoms among adults aged 18 to 80 diagnosed with generalized anxiety disorder (GAD) based on DSM-5-TR criteria. Conducted over an 8-week period, this trial will assess symptom reduction across a diverse U.S. sample, addressing the current lack of randomized studies comparing these two treatments and aiming to provide clearer guidance for clinicians treating GAD.

</p>
  <iframe src="pdf/P8140.pdf" width="100%" height="600px">
    This browser does not support PDFs. Please download the PDF to view it: <a href="pdf/P8140.pdf">Download PDF</a>.
  </iframe>
</div>
