---
title: "Publications & Research Experience"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
  body {
    text-align: justify; 
  }

  h2 {
    font-weight: bold; 
    font-size: 22px; 
    margin-top: 20px; 
    margin-bottom: 20px; 
    margin-left: 0; 
    text-indent: 0; 
  }
  
  p, .course-summary {
    font-size: 18px; 
  }

  .navbar {
    position: fixed;
    width: 100%;
    z-index: 999; 
  }
</style>
<script>
document.addEventListener("DOMContentLoaded", () => {
  const headerHeight = 200; 

  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
    anchor.addEventListener('click', function (e) {
      e.preventDefault(); 
      const targetId = this.getAttribute('href');
      const targetElement = document.querySelector(targetId);

      if (targetElement) {
        const elementTop = targetElement.getBoundingClientRect().top + window.pageYOffset;
        const scrollToPosition = elementTop - headerHeight; 

        window.scrollTo({
          top: scrollToPosition,
          behavior: 'smooth'
        });
      }
    });
  });
});
</script>


  <h2>1&#46; Publication links</h2>
  <p>
- [Li, R., Zhang, Q., Rao, A., Huo, Z., Da, W., Hao, X. (2023). The causal relationship between insomnia and major depressive disorder: a Mendelian randomization analysis. Military Medical Journal of South China, 37.02:140-3. (Chinese full text with English abstract) ](https://www.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2023&filename=HNGY202302011&uniplatform=OVERSEA&v=xGXFm1JokIhOzGldnmXUi-m6yZkeaTx0wGBb-LFK2caBOO1RFV0G3Vl6_bI1OUoY)

- [He, M., Fan, J., Zhou, R., Gao, G., Li, R., et al.(2022). NLRP3/Caspase-1-Mediated Pyroptosis of Astrocytes Induced by Antipsychotics Is Inhibited by a Histamine H1 Receptor-Selective Agonist. Frontiers in aging neuroscience, 14, 847561.](https://www.frontiersin.org/journals/aging-neuroscience/articles/10.3389/fnagi.2022.847561/full)

- [Zhou, R., He, M., Fan, J., Li, R., Zuo, Y., et al. (2022). The role of hypothalamic endoplasmic reticulum stress in schizophrenia and antipsychotic-induced weight gain: A narrative review. Frontiers in neuroscience, 16, 947295.](https://www.frontiersin.org/journals/neuroscience/articles/10.3389/fnins.2022.947295/full)
</p>

  <h2>2&#46; Research Experience</h2>

- [2.1. Optimization of Joint Fairness Model through Angle-Based Similarity Penalty Integration](#RE_project1)

- [2.2. Expression profile of plasma microRNAs associated with polycyclic aromatic hydrocarbon exposure](#RE_project2)

- [2.3. The Causal Relationship between Insomnia and Major Depressive Disorder: A Mendelian Randomization Analysis](#RE_project3)

- [2.4. The Effect of Antipsychotics on Astrocyte Pyroptotic Signaling & Molecular Mechanisms](#RE_project4)

<div id="RE_project1">
  <h2>2.1. Optimization of Joint Fairness Model through Angle-Based Similarity Penalty Integration</h2>
  <p>
- Graduate Practicum, 05/2024-Present

- Supervisor: Professor. Tian Gu, Assistant Professor, Department of Biostatistics, Columbia University Mailman School of Public Health

- Review fairness modeling approaches in supervised learning and develop a model optimizing the existing Joint Fairness Model with an Angle-Based Similarity Penalty, ensuring fairness and high prediction across diverse populations.

- Conduct Python simulations to evaluate the model against existing models across broad scenarios.
</p>
</div>

<div id="RE_project2">
  <h2>2.2. Expression profile of plasma microRNAs associated with polycyclic aromatic hydrocarbon exposure</h2>

  <p>
- Undergraduate Thesis (Chinese full text with English Abstract in Page III-Page IV), 12/2022-05/2023

- Supervisor: Professor. Tangchun Wu, Academician of Chinese Academy of Engineering; Dean of Tongji Medical College of Huazhong University of Science and Technology 

- [2.2.1. English Abstract Short Version](#RE_project2.1)

- [2.2.2. Chinese Full Text with English Abstract (Page III - Page IV)](#RE_project2.2)
</p>

<div id="RE_project2.1">
  <h2>2.2.1. English Abstract Short Version</h2>
  <p>
Introduction: Polycyclic aromatic hydrocarbons (PAHs) are linked to changes in microRNA (miRNA) expression, affecting gene expression and various biological processes. This study aims to explore miRNAs associated with PAH exposure in a generally healthy community population, seeking to understand the potential health effects and biological mechanisms involved.

Methods: In the Shiyan community, 160 participants were studied, measuring urinary monohydroxy PAHs and plasma benzo[a]pyrene-diol-epoxide adducts as PAH exposure biomarkers. Plasma miRNA levels were quantified using RNA sequencing, with relationships assessed via multivariable linear regression. Stratified and interaction analyses considered factors like age, sex, BMI, and smoking status. Candidate target genes for identified miRNAs were explored using several databases, with gene function enrichment analyzed via the DAVID database.

Results: Significant associations were found between specific PAH metabolites and 42 miRNAs, with four showing strong connections under more rigorous criteria. Stratified analyses highlighted age, smoking status, and BMI as influential factors in these relationships. Target gene functions for these miRNAs were linked to several critical biological processes and diseases, indicating broad systemic effects.

Conclusions: This study identified specific miRNAs significantly associated with PAH exposure in a generally healthy community, implicating these miRNAs in potentially mediating health impacts like cancer, cardiovascular diseases, and immune responses. These findings suggest that miRNAs could be crucial in the body's response to environmental toxins.

</p>
</div>
<div id="RE_project2.2">
  <h2>2.2.2. Chinese Full Text with English Abstract</h2>
  <iframe src="pdf/RE_2.pdf" width="100%" height="600px">
    This browser does not support PDFs. Please download the PDF to view it: <a href="pdf/RE_2.pdf">Download PDF</a>.
  </iframe>

</div>


<div id="RE_project3">
  <h2>2.3. The Causal Relationship between Insomnia and Major Depressive Disorder: A Mendelian Randomization Analysis</h2>

  <p>
- Student Researcher & Program Leader, 04/2020-04/2022  

- Supervisor: Professor Chaolong Wang, Professor and Deputy Dean, Department of Epidemiology and Biostatistics, School of Public Health, Huazhong University of Science and Technology

- This funded provincial Undergraduate Training Program in Innovation and Entrepreneurship was initiated and led by me, in collaboration with four classmates under the guidance of Professor Chaolong Wang.

- My responsibilities included organizing and analyzing genome-wide association studies data from 700,000 individuals in the UK Biobank and Million Veteran Program using R. I conducted bidirectional Mendelian randomization analysis to investigate the causal relationship between insomnia and major depressive disorder.

- Resulted in a first-author publication. Professor Xingjie Hao served as the corresponding author and the advisor throughout the writing and publication process.

- Chinese Full Text with English Abstract: [Li, R., Zhang, Q., Rao, A., Huo, Z., Da, W., Hao, X. (2023). The causal relationship between insomnia and major depressive disorder: a Mendelian randomization analysis. Military Medical Journal of South China, 37.02:140-3. (in Chinese) ](https://www.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2023&filename=HNGY202302011&uniplatform=OVERSEA&v=xGXFm1JokIhOzGldnmXUi-m6yZkeaTx0wGBb-LFK2caBOO1RFV0G3Vl6_bI1OUoY)

</div>

<div id="RE_project4">
  <h2>2.4. The Effect of Antipsychotics on Astrocyte Pyroptotic Signaling & Molecular Mechanisms</h2>
  
- Research Assistant, 01/2021-01/2023  

- Supervisor: Professor Meng He, Assistant Professor, Department of Pharmaceutical Engineering, Wuhan University of Technology                                            

- Assisted with data collection from the experiment and supported the statistical analysis process, including one-way ANOVA and Dunnett’s t-test in SPSS. Contributed to result interpretation and to the publication: [He, M., Fan, J., Zhou, R., Gao, G., Li, R., et al.(2022). NLRP3/Caspase-1-Mediated Pyroptosis of Astrocytes Induced by Antipsychotics Is Inhibited by a Histamine H1 Receptor-Selective Agonist. Frontiers in aging neuroscience, 14, 847561.](https://www.frontiersin.org/journals/aging-neuroscience/articles/10.3389/fnagi.2022.847561/full)

- Contributed to a literature review regarding the role of hypothalamic stress in antipsychotic-induced weight gain: [Zhou, R., He, M., Fan, J., Li, R., Zuo, Y., et al. (2022). The role of hypothalamic endoplasmic reticulum stress in schizophrenia and antipsychotic-induced weight gain: A narrative review. Frontiers in neuroscience, 16, 947295.](https://www.frontiersin.org/journals/neuroscience/articles/10.3389/fnins.2022.947295/full)
</p>
</div>


